### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by DSLituiev** [MicrosoftGenomics/FaST-LMM#9] opened 2015-09-25 22:45 UTC
I am getting while running a testfile `python3 tests/test.py`:

```
Traceback (most recent call last):
  File "tests/test.py", line 9, in <module>
    from fastlmm.association.FastLmmSet import FastLmmSet
  File "//anaconda/lib/python3.4/site-packages/fastlmm-0.2.17-py3.4-macosx-10.5-x86_64.egg/fastlmm/association/__init__.py", line 2, in <module>
    from fastlmm.association.single_snp import single_snp
  File "//anaconda/lib/python3.4/site-packages/fastlmm-0.2.17-py3.4-macosx-10.5-x86_64.egg/fastlmm/association/single_snp.py", line 13, in <module>
    from fastlmm.inference.lmm_cov import LMM as fastLMM
  File "//anaconda/lib/python3.4/site-packages/fastlmm-0.2.17-py3.4-macosx-10.5-x86_64.egg/fastlmm/inference/lmm_cov.py", line 806
    r2 = YKY[np.newaxis,:] - variance_explained_beta
                                                    ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by DSLituiev** [comment] 2015-09-25 22:52
after fixing that:
```
  File "tests/test.py", line 9, in <module>
    from fastlmm.association.FastLmmSet import FastLmmSet
  File "/Users/dlituiev/external/FaST-LMM/fastlmm/association/FastLmmSet.py", line 18, in <module>
    from fastlmm.association.tests import *
  File "/Users/dlituiev/external/FaST-LMM/fastlmm/association/tests/__init__.py", line 26, in <module>
    from . import LRT_up as lrt
  File "/Users/dlituiev/external/FaST-LMM/fastlmm/association/tests/LRT_up.py", line 81, in <module>
    class LRT_up(object):
ValueError: 'lrt' in __slots__ conflicts with class variable
```

**Comment by jennilis** [comment] 2015-09-26 17:56
Can you give us some sample files and script to reproduce the error?

**Comment by DSLituiev** [comment] 2015-09-28 16:19
I just `git clone`d your repository and ran `2to3`. Then `python3 setup.py install`. 
I used the test files from your repository, namely running `python3 tests/test.py` (this is after `2to3`).

Looking in your source, for example above mentioned [lmm_cov.py, line 30](https://github.com/MicrosoftGenomics/FaST-LMM/blob/master/fastlmm/inference/lmm_cov.py#L30) you can see that the file uses tabs for indentation which is against the [Python standard, which requires to use spaces only](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces)

**Comment by jennilis** [comment] 2015-09-29 12:27
Thanks. Dmytro. I’ll defer to the other on this.

**Comment by clippert** [comment] 2015-09-29 14:35
Hi Dmytro,

Note that we have not tested any of our code under Python 3.0 so far.

Also the use of tabs, even though violating a style guide, if done consistently should not affect how the code the code runs.
My assumption is that 2to3 modifies the code and while doing so creates inconstancies, mixing up tabs and spaces, which in turns breaks the script.

Cheers,
Christoph

From:  Jennifer Listgarten
Reply-To:  MicrosoftGenomics/FaST-LMM
Date:  Tuesday, September 29, 2015 at 5:27 AM
To:  MicrosoftGenomics/FaST-LMM
Subject:  Re: [FaST-LMM] TabError: inconsistent use of tabs and spaces in indentation (#9)

Thanks. Dmytro. I’ll defer to the other on this.

**Comment by schae234** [comment] 2016-02-10 17:11
Hi all,

Does anyone know if this was resolved? And if so, would you be willing to share or maybe make a python3 branch? We'd really like to use this in our workflow, and would be willing to contribute changes if you think this is feasible to get working with python3.

Thanks!

**Comment by DSLituiev** [comment] 2016-02-10 20:27
Good idea. I was able to fix indentations but there other issues with Python3 compatibility

**Comment by CarlKCarlK** [comment] 2016-02-13 01:09
DSLituiev, Thanks for your pull request. After some git-confusion on my part, I think I've checked in the tab fixes. For now, however, I haven't checked in the other Python 3 changes because they would apparently make Python 2.7 slower. [For example, Changing "xrange" to "range" and changing "range" to "list range" creates extra copying for Python 2.7.] Thanks for your interest in FastLMM and in compatibility with Python 3. I'd love to support Python 2.7 and 3, but I need to study the issue some more.
- Carl
p.s. A cartoon that expresses my feeling about Git: http://xkcd.com/1597/

**Closed by CarlKCarlK** 2016-02-13 01:09 UTC

**Comment by DSLituiev** [comment] 2016-02-13 01:31
Right. I think for xrange one can use `six` package.

**Comment by podpearson** [comment] 2017-01-17 11:24
Hi. Has there been any further work towards a Python 3 version of fastlmm? Thanks!

**Comment by jlistgarten** [comment] 2017-01-17 12:56
As far as I know, none of us are working on that. But I’ll let my colleagues confirm from their ends.

**Comment by heckerma** [comment] 2017-01-17 15:05
Hi Richard,

We periodically review requests and implement some of them.  If you send us your requests, we will add them to our list for consideration.

Best,

David
